apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2  # We want to run two instances of the backend
  selector:
    matchLabels:
      app: backend  # This selector helps to identify which pods belong to the backend service
  template:
    metadata:
      labels:
        app: backend  # Each pod created by this deployment will have this label
    spec:
      containers:
      - name: backend  # The container name, typically matching the app name
        image: <your-dockerhub-username>/backend  # Docker image for the backend service (replace <your-dockerhub-username>)
        ports:
        - containerPort: 5000  # The backend container will expose port 5000 (this is the Flask app's port)

