version: '3.7'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" # Map backend service to port 5000

  frontend:
    build: ./frontend
    ports:
      - "8081:80"   # Map frontend service to port 8080

