apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2  # Two instances of the frontend service
  selector:
    matchLabels:
      app: frontend  # This selector helps to identify which pods belong to the frontend service
  template:
    metadata:
      labels:
        app: frontend  # Each pod created by this deployment will have this label
    spec:
      containers:
      - name: frontend  # The container name, typically matching the app name
        image: <your-dockerhub-username>/frontend  # Docker image for the frontend service (replace <your-dockerhub-username>)
        ports:
        - containerPort: 80  # The frontend container will expose port 80 (default HTTP port)

